In [14]:
import numpy as np 
var1= np.array(([2,4,"Shilpa"],[1,3,5]))

# 

In [15]:
var1

array([['2', '4', 'Shilpa'],
       ['1', '3', '5']], dtype='<U11')

In [9]:
var2 = np.array(([1,3,5],[2,4,6]))

In [10]:
var1+var2

array([[ 3,  7, 11],
       [ 3,  7, 11]])

In [11]:
var1.itemsize

4

In [12]:
type(var1)

numpy.ndarray

In [16]:
var1.dtype

dtype('<U11')

In [17]:
var1.ndim

2

In [19]:
list

array([[1, 3, 5],
       [2, 4, 6]])

In [20]:
list.itemsize

4

In [22]:
list.size

6

In [26]:
list.shape

(2, 3)

In [24]:
list.reshape(3,2)

array([[1, 3],
       [5, 2],
       [4, 6]])

In [27]:
np.linspace(10,55,5)

array([10.  , 21.25, 32.5 , 43.75, 55.  ])

In [18]:
list = np.array([(1,3,5),(2,4,6)])

In [28]:
list[0:2,0:2]

array([[1, 3],
       [2, 4]])

In [29]:
list.max()

6

In [30]:
list.min()

1

In [31]:
list.sum()

21